# Configure Node.jS environment
language: node_js
node_js:
  - "stable"
install:
  - npm ci
cache: npm
jobs:
  include:
    - stage: "Run Cypress e2e"
      script: npm run e2e
    - stage: "Build app"
      if: branch = master
      script: npm run build
    - stage: "Deploy to Github Pages"
      deploy:
        script: echo 'skipping tests and deploying to Github pages'
        provider: pages
        cleanup: true
        github_token: $github_token
        local_dir: build
        on:
          branch: master